from km.constants import (
    DEFAULT_DATABASE_URI,
    DEFAULT_MODEL_NAME,
    DEFAULT_SERIALIZED_MODELS_DIR,
)


class Config:
    PORT = 5001
    DATABASE_URI = DEFAULT_DATABASE_URI
    SERIALIZED_MODEL_DIR = DEFAULT_SERIALIZED_MODELS_DIR
    SERIALIZED_MODEL_NAME = DEFAULT_MODEL_NAME + ".pkl"
